spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:50000}/${POSTGRES_DB:admin_bd}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

jwt.access.secret=${JWT_ACCESS_SECRET:7Yp2QZJkN6xM9H8Wc4FvR0L1uA+EwX3Tq5S/9mDObaJrKZVtCsiUeYlPhg==}
jwt.refresh.secret=${JWT_REFRESH_SECRET:Qw9fK3M1rT8bS+E4V6yA0D2LJXxZpHcN5UFeo7WgYI/kBmaRsdnCOT==}
jwt.access.ttl-minutes=${JWT_ACCESS_TTL_MINUTES:15}
jwt.refresh.ttl-hours=${JWT_REFRESH_TTL_HOURS:168}

server.port=${SERVER_PORT:8443}
server.ssl.enabled=${SSL_ENABLED:true}
server.ssl.key-store=${KEYSTORE_PATH:${KEYSTOR_PATH:file:./secrets/tls-1BIB23225/airline_keystore_1BIB23225.p12}}
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${KEYSTORE_PASSWORD:${KEYSTOR_PASSWORD:admin11}}
server.ssl.key-alias=${KEYSTORE_ALIAS:airline}